.PHONY: staticlib dynamiclib

staticlib : $(MATRIX_DIR)/libmatrix.o
# TO COMPLETE

dynamiclib : $(MATRIX_DIR)/libmatrix_shared.o
# TO COMPLETE

$(MATRIX_DIR)/libmatrix.o : $(MATRIX_DIR)/matrix.c
# TO COMPLETE

$(MATRIX_DIR)/libmatrix_shared.o : $(MATRIX_DIR)/matrix.c
# TO COMPLETE
